--- 
- 
  become: true
  hosts: default
  remote_user: vagrant
  tasks: 
    - 
      apt: 
        deb: "http://archive.cloudera.com/cdh5/one-click-install/precise/amd64/cdh5-repository_1.0_all.deb"
      name: "Step 1 - Install CDH5 1-click Install"
    - 
      apt_key: 
        url: "https://archive.cloudera.com/cdh5/ubuntu/precise/amd64/cdh/archive.key"
      name: "Step 2 - Add a Repository Key"
    - 
      apt: update_cache=yes
      name: Apt-get-Update
    - 
      apt: 
        name: "{{ packages }}"
      name: "Install JDK and JRE"
      vars: 
        packages: 
          - openjdk-7-jre
          - openjdk-7-jdk
    - 
      apt: 
        name: hadoop-0.20-conf-pseudo
        update_cache: true
      name: "Step 3 - Install hadoop"
