---
- hosts: default
  remote_user: vagrant
  become: yes
  tasks:
    - name: Añadir repositorio de cloudera Hadoop
      apt_repository: repo="deb [arch=amd64] http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/ trusty-cdh5 contrib" 
      state: present

    - name: Añadir repositorio src de cloudera Hadoop
      apt_repository: repo="deb-src http://archive.cloudera.com/cdh5/ubuntu/trusty/amd64/cdh/ trusty-cdh5 contrib" 
      state: present

    - name: Apt-get-Update
      apt: update_cache=yes 

